# Generated by Django 5.0.4 on 2024-04-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='token',
            new_name='refresh_token',
        ),
    ]
